import { Header } from "@/widgets/header";
import "./styles/style.scss";
import type { Metadata } from "next";
import { Footer } from "@/widgets/footer";
import { Aside } from "@/widgets/aside";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body>
        <Header />
        <section className="main">
          <Aside />
          <div className="image">
            {children}
            <Footer />
          </div>
        </section>
      </body>
    </html>
  );
}
